### ISSUE TITLE
Set up deployment to Heroku

### ISSUE THREAD

**Issue by jimcv** [mcgillcssa/cssa-frontend#14]
### Deploy backend and frontend to Heroku.
Repository Reference: https://github.com/McGill-ECSE321-Winter2022/project-group-group-05
Tutorial Reference: https://mcgill-ecse321-winter2022.github.io/

**Comment by jimcv** [comment]
Repository Reference: https://github.com/McGill-ECSE321-Winter2022/project-group-group-05
Tutorial Reference: https://mcgill-ecse321-winter2022.github.io/

**Comment by QCrow** [comment]
Closed by PR #22
