### ISSUE TITLE
Benefits page: the user shall be able to see a list of all merchants

### ISSUE THREAD

**Issue by jimcv** [mcgillcssa/cssa-frontend#15]
- the benefits page (/membership/benefits) is **NOT** the same page as the membership page (/membership), in the future, the user will be able to click on a button on the membership page to open the benefits page in a new tab
- the benefits page does not provide navigation to other pages (i.e. remove the navbar)
- make sure this page is displayed correctly on phone screen
- the main way of accessing this page is through redirect by the QR code endpoint
- the actual list of merchant (and pictures) will be given later, use dummy pictures for now

## 竖屏预览
![image](https://github.com/mcgillcssa/cssa-frontend/assets/71361453/34f46344-001e-4037-963d-7cda5fe350fb)
![image](https://github.com/mcgillcssa/cssa-frontend/assets/71361453/7d1dedfa-6449-44f2-abac-fe67f05062b2)

## 横屏（长屏预览）（如果困难的话，按照竖屏预览做就行）
![image](https://github.com/mcgillcssa/cssa-frontend/assets/71361453/f8fcfff7-0fed-459e-a51f-857ae8d8af28)

**Comment by QCrow** [comment]
Resolved by #41 as the first version of the page is finished.
