### ISSUE TITLE
Benefits page: the user shall be able to see discount details by clicking on a merchant

### ISSUE THREAD

**Issue by jimcv** [mcgillcssa/cssa-frontend#16]
- when a merchant picture is clicked, open a popup or slide down box with the details
- the details box should be able to display a slideshow of merchant photos

## Preview
![image](https://github.com/mcgillcssa/cssa-frontend/assets/71361453/00a1cc50-a9ac-4fff-b2aa-0bdd735a77bc)

**Comment by QCrow** [comment]
Resolved by #41 as the first version of the page is finished.
