### ISSUE TITLE
QR code endpoint

### ISSUE THREAD

**Issue by jimcv** [mcgillcssa/cssa-frontend#18]
### QR code endpoint
- provide an URL for redirecting QR code scans from the membership card (e.g. https://www.mcgillcssa.ca/access/qrscan)
- for now, all this link should do is **redirecting** the user to the actual membership/benefits page (e.g. https://www.mcgillcssa.ca/membership/benefits)
- in the future, we would like to be able to do more with the URL, such as counting the number of times the QR code has been scanned

**Deliverable: URL for the QR code**

**Comment by QCrow** [comment]
Closed by PR #25
